name: first-working-poccess
on:
  push:
    branches:
      - 'main'
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running unit-tests"
      - run: main.py
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy"
  production:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running production"

      
