name: first-working-poccess
on:
  push:
    branches:
      - 'main'
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pytest
      - run: ls
      - run: pytest unit_tests/unit_test.py
      - run: echo "Running unit-tests"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy"
  production:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running production"

      
