name: first-working-poccess
on:
  push:
    branches:
      - 'main'
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running unit-tests"
      - name: Install_pytest
        run: pip install pytest
      - name : Uses_my_code
        uses: actions/checkout@v3
      - name: Run_pytest
        run: pytest unit_tests/unit_test.py
        env:
            BOTNAME: BlueLockBot
            shell: bash
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy"
      - run: echo I am Roma > outlog.py
      - name: OutputFile
        uses: actions/upload-artifact@v3
        with:
          name: out-log-artifact
          path: outlog.py
    needs: unit_test
  production:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running production"
      - name: Check_artifact
        uses: actions/download-artifact@v3
        with:
          name: out-log-artifact
      - name: Run
        run: cat outlog.py
    needs: deploy
        

      
