name: first-working-poccess
on:
  push:
    branches:
      - 'main'
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running unit-tests"
      - name: Install_pytest
        run: pip install pytest
      - name : Uses_my_code
        uses: actions/checkout@v3
      - name: Run_pytest
        run: pytest unit_tests/unit_test.py
        env:
            BOTNAME: BlueLockBor
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running deploy"
  production:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running production"

      
