name: first-working-poccess
on: [push]
jobs:
  unit_test:
    runs-on: self-hosted 
    steps:
      - run: echo "Running unit-tests"
  deploy:
    runs-on: self-hosted
    steps:
      - run: echo "Running deploy"
  production:
    runs-on: self-hosted
    steps:
      - run: echo "Running production"

      
